### ISSUE TITLE
[Feature Request] Mass importer

### ISSUE THREAD

**Issue by ogreenz** [securancy/mass-smuggler#2]
Pretty straight forward after I export all of my databases to a folder I'd like a way to import them with the same easiness as I exported them. This makes life so much easy to just clone the a ravenDB without the database somewhere else.

**Comment by hanssens** [comment]
@ogreenz Makes sense. However, is there something specific missing from the [Raven.Backup tool](https://ravendb.net/docs/article-page/3.5/csharp/server/administration/backup-and-restore) that you would require in this mass-smuggler tool?

**Comment by Malavos** [comment]
I know this is an old issue, but I would just like to point out that with the backup tool, not only does it makes very easy to import, with ravendb cloud (don't know if many people are using it), make it kinda pointless.

We are using mass smuggler for a older ravendb 3 instance. But even with that huge old database, we never found a use for an "Mass importer". Can we close this? :)

**Comment by hanssens** [comment]
Agreed. Closing now because Raven 4 has built-in functionality for it. 
Although, as you mention yourself @Malavos, it's still useful for 3.x instances.
